# Generated by Django 5.2.13 on 2026-04-27 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('DsmppUsername', models.CharField(max_length=255)),
                ('FsmppUsername', models.CharField(max_length=255)),
                ('smppPassword', models.CharField(max_length=255)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puskarclient_created', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puskarclient_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'squadServices_puskar_client',
                'ordering': ['-updatedAt'],
            },
        ),
    ]
