# Generated by Django 5.2.13 on 2026-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlrApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updatedBy',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(help_text='Manual ID entry', primary_key=True, serialize=False),
        ),
    ]
