# Generated by Django 5.2.12 on 2026-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlrApp', '0002_remove_client_createdby_remove_client_updatedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expireDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
