# Generated by Django 5.2.12 on 2026-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dlrApp", "0004_alter_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_limit",
            field=models.IntegerField(default=0),
        ),
    ]
